language: elixir
sudo:     required
addons:
  postgresql: "9.6"
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then atlas deploy $SERVICE; fi
before_install:
  - curl -u '6aeac72bf78c789d48eafaa1e40972824baad6f4:' 'https://raw.githubusercontent.com/RallySoftware/atlas/master/install' | bash
  - nvm install 7
  - cd bin && npm install && cd ..
  - pip install --upgrade pip
before_script:
  - nvm install 7
  - atlas build $SERVICE
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.4.0
env:
  - SERVICE=web
git:
  depth: 999
install:
  - nvm install 7
  - atlas install $SERVICE
otp_release:
  - 19.2
script:
  - nvm install 7
  - atlas test $SERVICE
services:
  - docker
  - postgresql