language: elixir
sudo:     required
before_install:
  - ATLAS_PREFIX=$(pwd)
  - PATH=$PATH:$ATLAS_PREFIX
  - curl -u '6aeac72bf78c789d48eafaa1e40972824baad6f4:' 'https://raw.githubusercontent.com/RallySoftware/atlas/master/install' | bash
before_script:
  - atlas build $SERVICE
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.4.0
env:
  - SERVICE=web
git:
  depth: 999
install:
  - atlas install $SERVICE
otp_release:
  - 19.2
script:
  - atlas test $SERVICE
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then atlas deploy $SERVICE; fi
services:
  - docker
